download:
    dataset: "MNIST"

model:
    n_classes: 10
    dropout: 0.5
    accelerator: "cpu"

train:
    learning_rate: 1e-3
    batch_size: 64
    n_epochs: 5
    random_seed: 42
    model_save: "model.pth"
    model_save_onnx: "model.onnx"
    devices: "auto"

artifacts:
    experiment_name: "mlops"
    tracking_uri: "file:./logs"

callbacks:
    max_depth: 3

infer:
    batch_size: 64
    model_load: "model.pth"
    preds_file: "labels.csv"
