download:
    dataset: "MNIST"

train:
    learning_rate: 1e-3
    batch_size: 64
    n_epochs: 5
    n_classes: 10
    random_seed: 42
    model_save: "model.pth"

infer:
    batch_size: 64
    model_load: "model.pth"
    preds_file: "labels.csv"
